print('Olá, tchurma')
print("Cachaça")
print('Olá', 'Vanderlei', 'Diter', 'Gabriel', 'Felipe')
print('Olá', '\nVanderlei', '\nDiter', '\nGabriel', '\nFelipe')
print('Olá', '\n\tVanderlei', '\n\tDiter', '\n\tGabriel', '\n\tFelipe')